'use client'
import { useState } from 'react'
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { Menu, X } from 'lucide-react'
import { SITE_CONFIG } from '@/lib/site-config'
import { useEditableLocalAuthSession } from '@/editable/components/EditableLocalAuthForms'
const links=[{label:'Classified',href:'/classified'},{label:'Home',href:'/'},{label:'About',href:'/about'},{label:'Search',href:'/search'}]
export function EditableNavbar(){const[open,setOpen]=useState(false),pathname=usePathname(),{session,logout}=useEditableLocalAuthSession();return <header className="sticky top-0 z-50 border-b border-[var(--editable-border)] bg-white/95 backdrop-blur-xl"><nav className="mx-auto flex min-h-[92px] max-w-[1280px] items-center gap-8 px-5 sm:px-8"><Link href="/" className="editable-display mr-auto flex items-center gap-3 text-xl font-extrabold tracking-[-.04em] text-[#073032] sm:text-2xl"><span className="flex h-14 w-14 shrink-0 items-center justify-center overflow-hidden rounded-2xl bg-[#e4faf3] p-1"><img src="/favicon.png" alt="" className="h-full w-full scale-110 object-contain" /></span><span>{SITE_CONFIG.name}</span></Link><div className="hidden items-center gap-7 lg:flex">{links.map(i=><Link key={i.href} href={i.href} className={`text-sm font-semibold transition ${pathname===i.href?'text-[var(--slot4-accent)]':'text-[#073032] hover:text-[var(--slot4-accent)]'}`}>{i.label}</Link>)}</div><div className="hidden items-center gap-3 sm:flex">{session?<><span className="max-w-36 truncate text-sm font-bold text-[#073032]">{session.name}</span><Link href="/create" className="rounded-lg bg-[var(--slot4-accent)] px-4 py-2.5 text-sm font-bold text-white">Create</Link><button onClick={logout} className="rounded-lg border border-[var(--editable-border)] px-4 py-2.5 text-sm font-bold text-[#073032]">Logout</button></>:<><Link href="/login" className="rounded-lg border border-[var(--editable-border)] px-4 py-2.5 text-sm font-bold text-[#073032]">Login</Link><Link href="/signup" className="rounded-lg bg-[var(--slot4-accent)] px-4 py-2.5 text-sm font-bold text-white">Sign up</Link></>}</div><button onClick={()=>setOpen(v=>!v)} className="rounded-lg border border-[var(--editable-border)] p-2 lg:hidden" aria-label="Toggle menu">{open?<X/>:<Menu/>}</button></nav>{open&&<div className="border-t border-[var(--editable-border)] bg-white px-5 py-5 lg:hidden"><div className="mx-auto grid max-w-[1280px] gap-2">{links.map(i=><Link onClick={()=>setOpen(false)} key={i.href} href={i.href} className="rounded-lg px-3 py-3 font-bold text-[#073032] hover:bg-[#e4faf3]">{i.label}</Link>)}{session?<><div className="px-3 py-2 text-sm font-bold text-[var(--slot4-accent)]">{session.name}</div><Link href="/create" className="rounded-lg px-3 py-3 font-bold">Create</Link><button onClick={logout} className="rounded-lg px-3 py-3 text-left font-bold">Logout</button></>:<><Link href="/login" className="rounded-lg px-3 py-3 font-bold">Login</Link><Link href="/signup" className="rounded-lg bg-[var(--slot4-accent)] px-3 py-3 font-bold text-white">Sign up</Link></>}</div></div>}</header>}
