import Link from 'next/link'
import { ArrowRight, BriefcaseBusiness, MapPin, Search, ShieldCheck, Sparkles, Tag } from 'lucide-react'
import type { SitePost } from '@/lib/site-connector'
import type { HomeTimeSection } from '@/lib/task-data'
import type { TaskKey } from '@/lib/site-config'
import { getEditableCategory, getEditableExcerpt, getEditablePostImage, postHref } from '@/editable/cards/PostCards'

type Props = { primaryTask: TaskKey; primaryRoute: string; posts: SitePost[]; timeSections: HomeTimeSection[] }
const shell = 'mx-auto w-full max-w-[1280px] px-5 sm:px-8'
function merge(posts: SitePost[], sections: HomeTimeSection[]) { const seen = new Set<string>(); return [...posts, ...sections.flatMap(s => s.posts)].filter(p => { const k = p.slug || p.id || p.title; if (!k || seen.has(k)) return false; seen.add(k); return true }) }
const image = (post?: SitePost) => post ? getEditablePostImage(post) : '/placeholder.svg?height=900&width=1200'

export function EditableHomeHero({ primaryTask, primaryRoute, posts, timeSections }: Props) {
 const pool = merge(posts, timeSections), slides = pool.slice(0, 5)
 return <section className="overflow-hidden bg-white pb-14 pt-14 sm:pb-20 sm:pt-20"><div className={`${shell} text-center`}><p className="fa-reveal text-xs font-bold uppercase tracking-[.2em] text-[var(--slot4-accent)]">Focused classifieds</p><h1 className="fa-reveal mx-auto mt-5 max-w-4xl text-balance text-5xl font-semibold leading-[.98] tracking-[-.065em] sm:text-7xl lg:text-[5.5rem]">Find the right offer.</h1><p className="fa-reveal mx-auto mt-6 max-w-2xl text-lg leading-8 text-[var(--slot4-muted-text)]">Explore useful local products, services, jobs, rentals, and opportunities in one clear place.</p><form action="/search" className="fa-reveal mx-auto mt-9 flex max-w-2xl rounded-xl border border-[var(--editable-border)] bg-white p-1.5 shadow-[0_18px_55px_rgba(7,48,50,.12)]"><label className="flex min-w-0 flex-1 items-center gap-3 px-4"><Search className="h-5 w-5 shrink-0 text-[var(--slot4-accent)]" /><input name="q" aria-label="Search classifieds" placeholder="Search services, products, jobs..." className="min-w-0 flex-1 bg-transparent py-3 text-sm outline-none placeholder:text-slate-400" /></label><button className="rounded-lg bg-[var(--slot4-accent)] px-5 py-3 text-sm font-bold text-white sm:px-8">Search</button></form></div><div className="fa-hero-marquee mt-14 flex w-max gap-5 px-5">{[...slides, ...slides].map((post, i) => <Link key={`${post?.id || i}-${i}`} href={post ? postHref(primaryTask, post, primaryRoute) : primaryRoute} className={`fa-shape shape-${i % 5} group block h-72 w-64 shrink-0 overflow-hidden sm:h-80 sm:w-72`}><img src={image(post)} alt={post?.title || 'Featured classified'} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /></Link>)}</div><div className={`${shell} mt-12 grid gap-5 border-y border-[var(--editable-border)] py-7 sm:grid-cols-3`}>{[[ShieldCheck,'Clear details','Useful information at a glance'],[Sparkles,'Fresh discoveries','New classified opportunities'],[Tag,'Focused offers','Products, services, jobs, and rentals']].map(([Icon,t,d]) => <div key={String(t)} className="flex items-center gap-4 sm:justify-center"><Icon className="h-6 w-6 text-[var(--slot4-accent)]" /><div><p className="font-bold">{String(t)}</p><p className="text-sm text-[var(--slot4-muted-text)]">{String(d)}</p></div></div>)}</div></section>
}
export function EditableStoryRail({ primaryRoute }: Props) { return <section className="bg-[var(--slot4-warm)] py-20 sm:py-28"><div className={`${shell} grid items-center gap-12 lg:grid-cols-[.8fr_1.2fr]`}><div><p className="text-sm font-bold text-[var(--slot4-accent)]">A simpler way to discover</p><h2 className="mt-4 text-4xl font-semibold leading-[1.02] tracking-[-.05em] sm:text-6xl">Browse with purpose.</h2><p className="mt-6 max-w-lg text-lg leading-8 text-[var(--slot4-muted-text)]">Whether you are buying, selling, hiring, renting, or offering a service, start with clear classified details.</p><Link href={primaryRoute} className="mt-8 inline-flex rounded-lg bg-[var(--slot4-accent)] px-6 py-3.5 text-sm font-bold text-white">Explore classifieds</Link></div><Link href="/classified" className="fa-info-card group bg-[#073032] text-white"><BriefcaseBusiness className="h-9 w-9 text-[#42dfb2]" /><p className="mt-16 text-sm font-bold text-[#42dfb2]">CLASSIFIEDS</p><h3 className="mt-3 max-w-xl text-3xl font-semibold sm:text-4xl">Buy, sell, hire, rent, and offer—all in one focused marketplace.</h3><ArrowRight className="mt-8 transition group-hover:translate-x-2" /></Link></div></section> }
function Compact({ post, href }: { post: SitePost; href: string }) { const ex = getEditableExcerpt(post, 105); return <Link href={href} className="group flex min-w-[280px] max-w-[320px] shrink-0 gap-4 rounded-2xl border border-[var(--editable-border)] bg-white p-3 transition hover:-translate-y-1 hover:shadow-xl"><img src={image(post)} alt={post.title || 'Classified'} className="h-28 w-28 shrink-0 rounded-xl object-cover" /><div className="min-w-0 py-1"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[var(--slot4-accent)]">{getEditableCategory(post)}</p><h3 className="mt-2 line-clamp-2 font-bold leading-snug">{post.title || 'Untitled listing'}</h3>{ex ? <p className="mt-2 line-clamp-2 text-xs leading-5 text-[var(--slot4-muted-text)]">{ex}</p> : null}</div></Link> }
export function EditableMagazineSplit({ primaryTask, primaryRoute, posts, timeSections }: Props) { const pool = merge(posts,timeSections); if (!pool.length) return null; const first=pool[0]; return <section className="bg-white py-20 sm:py-28"><div className={shell}><div className="mb-10 flex items-end justify-between gap-4"><div><p className="text-sm font-bold text-[var(--slot4-accent)]">What’s available now</p><h2 className="mt-3 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">Fresh finds, clearly presented.</h2></div><Link href={primaryRoute} className="hidden items-center gap-2 font-bold sm:flex">View all <ArrowRight className="h-4 w-4" /></Link></div><Link href={postHref(primaryTask,first,primaryRoute)} className="group grid overflow-hidden rounded-[28px] border border-[var(--editable-border)] bg-white lg:grid-cols-[1.05fr_.95fr]"><div className="min-h-80 overflow-hidden"><img src={image(first)} alt={first.title || 'Featured classified'} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /></div><div className="flex flex-col justify-center p-8 sm:p-12"><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--slot4-accent)]">Featured opportunity</p><h3 className="mt-5 text-3xl font-semibold leading-tight tracking-[-.04em] sm:text-5xl">{first.title || 'Explore the latest opportunity'}</h3>{getEditableExcerpt(first) ? <p className="mt-5 line-clamp-3 leading-7 text-[var(--slot4-muted-text)]">{getEditableExcerpt(first,180)}</p> : null}<span className="mt-8 inline-flex items-center gap-2 font-bold">View details <ArrowRight className="h-4 w-4" /></span></div></Link><div className="fa-auto-rail mt-8 overflow-hidden"><div className="fa-auto-track flex w-max gap-4">{[...pool.slice(1,9),...pool.slice(1,9)].map((p,i)=><Compact key={`${p.id||p.slug}-${i}`} post={p} href={postHref(primaryTask,p,primaryRoute)} />)}</div></div></div></section> }
export function EditableTimeCollections({ primaryTask, primaryRoute, posts, timeSections }: Props) { const pool=merge(posts,timeSections).slice(0,4); if(pool.length<2)return null; return <section className="bg-[var(--slot4-warm)] py-20 sm:py-28"><div className={shell}><div className="text-center"><p className="text-sm font-bold text-[var(--slot4-accent)]">Offers worth exploring</p><h2 className="mt-3 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">More classifieds.</h2></div><div className="mt-12 grid gap-5 lg:grid-cols-2">{pool.map((p,i)=><Link key={p.id||p.slug} href={postHref(primaryTask,p,primaryRoute)} className={`group grid overflow-hidden rounded-2xl border border-[var(--editable-border)] bg-white ${i===0?'sm:grid-cols-[1.15fr_.85fr] lg:col-span-2':'sm:grid-cols-[160px_1fr]'}`}><img src={image(p)} alt={p.title||'Classified'} className="h-full min-h-52 w-full object-cover" /><div className="flex flex-col justify-center p-7"><p className="text-xs font-bold uppercase tracking-[.15em] text-[var(--slot4-accent)]">{getEditableCategory(p)}</p><h3 className={`${i===0?'text-4xl':'text-2xl'} mt-3 font-semibold leading-tight tracking-[-.035em]`}>{p.title||'Explore this classified'}</h3>{getEditableExcerpt(p)?<p className="mt-3 line-clamp-2 leading-6 text-[var(--slot4-muted-text)]">{getEditableExcerpt(p,120)}</p>:null}<span className="mt-5 inline-flex items-center gap-2 text-sm font-bold">View classified <ArrowRight className="h-4 w-4" /></span></div></Link>)}</div></div></section> }
export function EditableHomeCta(){return <section className="bg-white py-20 sm:py-28"><div className={`${shell} relative overflow-hidden rounded-[32px] bg-[#073032] px-7 py-16 text-center text-white sm:px-14 sm:py-24`}><MapPin className="fa-float absolute left-[10%] top-[20%] h-10 w-10 text-[#42dfb2]/35" /><Sparkles className="fa-float absolute bottom-[18%] right-[12%] h-12 w-12 text-[#42dfb2]/35" /><p className="text-sm font-bold text-[#42dfb2]">Have something to offer?</p><h2 className="mx-auto mt-4 max-w-3xl text-4xl font-semibold tracking-[-.05em] sm:text-6xl">Put your next classified in front of interested buyers.</h2><p className="mx-auto mt-5 max-w-xl text-lg leading-8 text-white/70">Create a clear classified with the information buyers need to respond.</p><Link href="/create" className="mt-8 inline-flex rounded-lg bg-[#42dfb2] px-7 py-3.5 font-bold text-[#073032]">Create a classified</Link></div></section>}
